from enum import Enum

class FormaPagoExportacionEnum(Enum):
    NotSet = (0, "No Asignado")
    COB1 = (1, "COB 1")
    ACRED = (11, "ACRED")
    CBOF = (12, "CBOF")
    COBRANZA = (2, "Cobranza")
    SINPAGO = (21, "Sin Pago")
    ANTICIPO = (32, "Anticipo")
    ANT_COB = (50, "Anticipo Cobranza")
    ANT_CRED = (60, "Anticipo Crédito")
    @property
    def xml_enum(self):
        return self.value[0]

    @property
    def description(self):
        return self.value[1]

class Moneda(Enum):
    NotSet = (0, "No Asignado")
    PESO = (1, "Peso")
    PESO_CHILENO = (200, "Peso Chileno")
    DOLAR_ESTADOUNIDENSE = (13, "Dolar Estadounidense")
    BOLIVAR = (134, "Bolivar")
    BOLIVIANO = (4, "Boliviano")
    CHELIN = (37, "Chelin")
    CORONA_DINAMARCA = (51, "Corona Din")
    CRUZEIRO_REAL = (5, "Cruzeiro Real")
    DIRHAM = (139, "Dirham")
    DOLAR_AUSTRALIANO = (36, "Dolar Australiano")
    DOLAR_CANADIENSE = (6, "Dolar Canadiense")
    EURO = (142, "Euro")
    FRANCO_BEL = (40, "Franco Belga")
    FRANCO_FR = (58, "Franco Francés")
    FRANCO_SZ = (82, "Franco Suizo")
    GUARANI = (23, "Guarani")
    LIBRA_EST = (102, "Libra Esterlina")
    LIRA = (71, "Lira")
    MARCO_AL = (30, "Marco Alemán")
    MARCO_FIN = (57, "Marco Finlandés")
    NUEVO_SOL = (24, "Nuevo Sol")
    OTRAS_MONEDAS = (900, "Otras Monedas")
    PESETA = (53, "Peseta")
    PESO_COL = (129, "Peso Colombiano")
    PESO_MEX = (132, "Peso Mexicano")
    PESO_URUG = (26, "Peso Uruguayo")
    RAND = (128, "Rand")
    RENMINBI = (48, "Renminbi")
    RUPIA = (137, "Rupia")
    SUCRE = (130, "Sucre")
    YEN = (72, "Yen")
    FLORIN = (64, "Florin")
    CORONA_NOR = (96, "Corona Noruega")
    DOLAR_NZ = (97, "Dólar Neozeolandés")
    CORONA_SC = (113, "Corona Sueca")
    DOLAR_HK = (127, "Dolar Hong Kong")
    DRACMA = (131, "Dracma")
    ESCUDO = (133, "Escudo")
    DOLAR_SIN = (136, "Dólar Singapur")
    DOLAR_TAI = (138, "Dólar Tailandés")

    @property
    def xml_enum(self):
        return self.value[0]

    @property
    def description(self):
        return self.value[1]

class ModalidadVenta(Enum):
    NotSet = (0, "No Asignado")
    A_FIRME = (1, "A Firme")
    BAJO_CONDICION = (2, "Bajo Condición")
    CONSIGNACION_LIBRE = (3, "Consignación Libre")
    CONSIGNACION_MINIMO_FIRME = (4, "Consignación Mínimo Firme")
    SIN_PAGO = (9, "Sin pago")
    @property
    def xml_enum(self):
        return self.value[0]

    @property
    def description(self):
        return self.value[1]

class ClausulaCompraVenta(Enum):
    NotSet = (0, "No Asignado")
    CIF = (1, "CIF")
    CFR = (2, "CFR")
    EXW = (3, "EXW")
    FAS = (4, "FAS")
    FOB = (5, "FOB")
    S_CLAUSULA = (6, "S Clausula")
    DDP = (9, "DDP")
    FCA = (7, "FCA")
    CPT = (11, "CPT")
    CIP = (12, "CIP")
    DAT = (17, "DAT")
    DAP = (18, "DAP")
    OTROS = (8, "Otros")

    @property
    def xml_enum(self):
        return self.value[0]

    @property
    def description(self):
        return self.value[1]

class ViasdeTransporte(Enum):
    NotSet = (0, "No Asignado")
    MARITIMA_FLUVIAL_Y_LACUSTRE = (1, "Maritima, Fluvial y Lacustre")
    AEREO = (4, "Aéreo")
    POSTAL = (5, "Postal")
    FERROVIARIO = (6, "Ferroviario")
    CARRETERO_O_TERRESTRE = (7, "Carretero o Terrestre")
    ELEODUCTOS_GASODUCTOS = (8, "Eleoductos y Gasoductos")
    TENDIDO_ELECTRICO = (9, "Tendido Eléctrico")
    OTRA = (10, "Otra")
    COURIER_AEREO = (11, "Courier Aéreo")

    @property
    def xml_enum(self):
        return self.value[0]

    @property
    def description(self):
        return self.value[1]

class UnidadMedida(Enum):
    NotSet = (0, "No Asignado")
    SUM = (0, "SUM")
    TMB = (1, "TMB")
    U = (10, "U")
    DOC = (11, "DOC")
    U_JGO = (12, "U JGO")
    MU = (13, "MU")
    MT = (14, "MT")
    MT2 = (15, "MT2")
    MCUB = (16, "MCUB")
    PAR = (17, "Par")
    KNFC = (18, "KNFC")
    CARTON = (19, "Cartón")
    QMB = (2, "QMB")
    KWH = (20, "KWH")
    BAR = (23, "BAR")
    M2_1MM = (24, "M2 1MM")
    MKWH = (3, "MKWH")
    TMN = (4, "TMN")
    KLT = (5, "KLT")
    KN = (6, "KN")
    GN = (7, "GN")
    HL = (8, "HL")
    LT = (9, "LT")

    @property
    def xml_enum(self):
        return self.value[0]

    @property
    def description(self):
        return self.value[1]


class TipoBultoEnum(Enum):
    NotSet = (0, "No Asignado")
    POLVO = (1, "Polvo")
    PIEZA = (10, "Pieza")
    TUBO = (11, "Tubo")
    CILINDRO = (12, "Cilindro")
    ROLLO = (13, "Rollo")
    BARRA = (16, "Barra")
    LINGOTE = (17, "Lingote")
    TRONCO = (18, "Tronco")
    BLOQUE = (19, "Bloque")
    GRANOS = (2, "Granos")
    ROLLIZO = (20, "Rollizo")
    CAJON = (21, "Cajón")
    CAJA_DE_CARTON = (22, "Caja de Cartón")
    FARDO = (23, "Fardo")
    BAUL = (24, "Baúl")
    COFRE = (25, "Cofre")
    ARMAZON = (26, "Armazón")
    BANDEJA = (27, "Bandeja")
    CAJAMADERA = (28, "Caja Madera")
    CAJALATA = (29, "Caja Lata")
    NODULOS = (3, "Nodulos")
    BOTELLAGAS = (31, "Botella a Gas")
    BOTELLA = (32, "Botella")
    JAULA = (33, "Jaula")
    BIDON = (34, "Bidón")
    JABA = (35, "Jaba")
    CESTA = (36, "Cesta")
    BARRILETE = (37, "Barrilete")
    TONEL = (38, "Tonel")
    PIPA = (39, "Pipa")
    LIQUIDO = (4, "Líquido")
    CAJANOESP = (40, "Caja No Esp")
    JARRO = (41, "Jarro")
    FRASCO = (42, "Frasco")
    DAMAJUANA = (43, "Damajuana")
    BARRIL = (44, "Barril")
    TAMBOR = (45, "Tambor")
    CUNETE = (46, "Cunete")
    TARRO = (47, "Tarro")
    GAS = (5, "Gas")
    CUBO = (51, "Cubo")
    PAQUETE = (61, "Paquete")
    SACO = (62, "Saco")
    MALETA = (63, "Maleta")
    BOLSA = (64, "Bolsa")
    BALA = (65, "Bala")
    RED = (66, "Red")
    SOBRE = (67, "Sobre")
    CONT20 = (73, "Cont20")
    CONT40 = (74, "Cont40")
    CONTENEDOR_REFRIGERADO = (75, "Contenedor Refrigerado")
    REEFER40 = (76, "Reefer40")
    ESTANQUE = (77, "Estanque")
    CONTNOESP = (78, "Cont No Esp")
    PALLET = (80, "Pallet")
    TABLERO = (81, "Tablero")
    LAMINA = (82, "Lámina")
    CARRETE = (83, "Carrete")
    AUTOMOTOR = (85, "Automotor")
    ATAUD = (86, "Ataúd")
    MAQUINARIA = (88, "Máquinaria")
    PLANCHA = (89, "Plancha")
    ATADO = (90, "Atado")
    BOBINA = (91, "Bobina")
    BULTONOESP = (93, "Bultoesp")
    SIN_BULTO = (98, "Sin Bulto")
    SIN_EMBALAR = (99, "Sin Embalar")

    @property
    def xml_enum(self):
        return self.value[0]

    @property
    def description(self):
        return self.value[1]


class Paises(Enum):
    NOT_SET = (0, "No Asignado")
    SENEGAL = (101, "Senegal")
    GAMBIA = (102, "Gambia")
    GUINEA_BISSAU = (103, "Guinea Bissau")
    GUINEA = (104, "Guinea")
    SIERRA_LEONA = (105, "Sierra Leona")
    LIBERIA = (106, "Liberia")
    COSTA_DE_MARFIL = (107, "Costa de Marfil")
    GHANA = (108, "Ghana")
    TOGO = (109, "Togo")
    NIGERIA = (111, "Nigeria")
    SUDAFRICA = (112, "Sudáfrica")
    BOTSWANA = (113, "Botswana")
    LESOTHO = (114, "Lesotho")
    MALAWI = (115, "Malawi")
    ZIMBABWE = (116, "Zimbabwe")
    ZAMBIA = (117, "Zambia")
    COMORAS = (118, "Comoras")
    MAURICIO = (119, "Mauricio")
    MADAGASCAR = (120, "Madagascar")
    MOZAMBIQUE = (121, "Mozambique")
    SWAZILANDIA = (122, "Swazilandia")
    SUDAN = (123, "Sudán")
    EGIPTO = (124, "Egipto")
    LIBIA = (125, "Libia")
    TUNEZ = (126, "Túnez")
    ARGELIA = (127, "Argelia")
    MARRUECOS = (128, "Marruecos")
    CABO_VERDE = (129, "Cabo Verde")
    CHAD = (130, "Chad")
    NIGER = (131, "Niger")
    MALI = (133, "Malí")
    MAURITANIA = (134, "Mauritania")
    TANZANIA = (135, "Tanzania")
    UGANDA = (136, "Uganda")
    KENIA = (137, "Kenia")
    SOMALIA = (138, "Somalia")
    ETIOPIA = (139, "Etiopía")
    ANGOLA = (140, "Angola")
    BURUNDI = (141, "Burundi")
    RWANDA = (142, "Rwanda")
    REP_DEM_CONGO = (143, "República Democrática del Congo")
    CONGO = (144, "Congo")
    GABON = (145, "Gabón")
    SANTO_TOME_PRINCIPE = (146, "Santo Tomé y Príncipe")
    GUINEA_ECUATORIAL = (147, "Guinea Ecuatorial")
    REP_CENTROAFRICANA = (148, "República Centroafricana")
    CAMERUN = (149, "Camerún")
    BENIN = (150, "Benín")
    TERR_BRIT_EN_AF = (151, "Territorio Británico en África")
    TERR_ESPAN_EN_AF = (152, "Territorio Español en África")
    TERR_FRAN_EN_AF = (153, "Territorio Francés en África")
    DJIBOUTI = (155, "Djibouti")
    SEYCHELLES = (156, "Seychelles")
    NAMIBIA = (159, "Namibia")
    SUDAN_DEL_SUR = (160, "Sudán del Sur")
    BURKINA_FASO = (161, "Burkina Faso")
    ERITREA = (163, "Eritrea")
    ISLAS_MARSHALL = (164, "Islas Marshall")
    SAHARAUI = (165, "Saharaui")
    VENEZUELA = (201, "Venezuela")
    COLOMBIA = (202, "Colombia")
    TRINIDAD_TOBAGO = (203, "Trinidad y Tobago")
    BARBADOS = (204, "Barbados")
    JAMAICA = (205, "Jamaica")
    REP_DOMINICANA = (206, "República Dominicana")
    BAHAMAS = (207, "Bahamas")
    HAITI = (208, "Haití")
    CUBA = (209, "Cuba")
    PANAMA = (210, "Panamá")
    COSTA_RICA = (211, "Costa Rica")
    NICARAGUA = (212, "Nicaragua")
    EL_SALVADOR = (213, "El Salvador")
    HONDURAS = (214, "Honduras")
    GUATEMALA = (215, "Guatemala")
    MEXICO = (216, "México")
    GUYANA = (217, "Guyana")
    ECUADOR = (218, "Ecuador")
    PERU = (219, "Perú")
    BRASIL = (220, "Brasil")
    BOLIVIA = (221, "Bolivia")
    PARAGUAY = (222, "Paraguay")
    URUGUAY = (223, "Uruguay")
    ARGENTINA = (224, "Argentina")
    U_S_A = (225, "Estados Unidos")
    CANADA = (226, "Canadá")
    TERR_BRIT_EN_AM = (227, "Territorio Británico en América")
    TERR_FRAN_EN_AM = (228, "Territorio Francés en América")
    TER_HOLAN_EN_AM = (229, "Territorio Holandés en América")
    TERR_D_DINAMARC = (230, "Territorio de Dinamarca")
    DOMINICA = (231, "Dominica")
    GRANADA = (232, "Granada")
    SANTA_LUCIA = (233, "Santa Lucía")
    S_VTE_Y_GRANAD = (234, "San Vicente y las Granadinas")
    SURINAM = (235, "Surinam")
    BELICE = (236, "Belice")
    ANTIGUA_Y_BBUDA = (240, "Antigua Y Barbuda")
    SNT_KIT_AND_NEVIS = (241, "Isla de San Cristóbal y Nieves")
    ANGUILA = (242, "Anguila")
    ARUBA = (243, "Aruba")
    BERMUDAS = (244, "Bermudas")
    ISLAS_VIRG_BRIT = (245, "Islas Vírgenes Británicas")
    ISLAS_CAYMAN = (246, "Islas Caimán")
    ANTILLAS_NEERLA = (247, "Antillas Neerlandesas")
    TURCAS_Y_CAICOS = (248, "Islas Turcas y Caicos")
    ISLAS_VIRG_EUA = (249, "Islas Vírgenes de los Estados Unidos")
    MARTINICA = (250, "Martinica")
    PUERTO_RICO = (251, "Puerto Rico")
    MONSERRAT = (252, "Montserrat")
    GROENLADIA = (253, "Groenlandia")
    JORDANIA = (301, "Jordania")
    ARABIA_SAUDITA = (302, "Arabia Saudita")
    KUWAIT = (303, "Kuwait")
    OMAN = (304, "Omán")
    CHIPRE = (305, "Chipre")
    ISRAEL = (306, "Israel")
    IRAK = (307, "Irak")
    AFGHANISTAN = (308, "Afganistán")
    IRAN = (309, "Irán")
    SIRIA = (310, "Siria")
    LIBANO = (311, "Líbano")
    QATAR = (312, "Qatar")
    BAHREIN = (313, "Bahréin")
    SRI_LANKA = (314, "Sri Lanka")
    CAMBODIA = (315, "Camboya")
    LAOS = (316, "Laos")
    INDIA = (317, "India")
    BUTAN = (318, "Bután")
    THAILANDIA = (319, "Tailandia")
    NEPAL = (320, "Nepal")
    BANGLADESH = (321, "Bangladesh")
    PALESTINA = (322, "Palestina")
    PAKISTAN = (324, "Pakistán")
    VIETNAM = (325, "Vietnam")
    MYANMAR_EX_BIR = (326, "Myanmar (Birmania)")
    ISLAS_MALDIVAS = (327, "Islas Maldivas")
    INDONESIA = (328, "Indonesia")
    MALASIA = (329, "Malasia")
    TAIWAN_FORMOSA = (330, "Isla de Taiwán")
    JAPON = (331, "Japón")
    SINGAPUR = (332, "Singapur")
    COREA_DEL_SUR = (333, "Corea del Sur")
    RPD_COREA_DEL_N = (334, "Corea del Norte")
    FILIPINAS = (335, "Filipinas")
    CHINA = (336, "China")
    MONGOLIA = (337, "Mongolia")
    EMIR_ARAB_UNID = (341, "Emiratos Árabes Unidos")
    HONG_KONG = (342, "Hong Kong")
    TER_PORTUG_EAS = (343, "Territorio Portugués en Asia")
    BRUNEI = (344, "Brunéi")
    MACAO = (345, "Macao")
    REPUBLICA_DE_YE = (346, "Yemen")
    FIJI = (401, "Fiji")
    NAURU = (402, "Nauru")
    ISLAS_TONGA = (403, "Islas Tonga")
    SAMOA_OCC = (404, "Samoa")
    NUEVA_ZELANDIA = (405, "Nueva Zelanda")
    AUSTRALIA = (406, "Australia")
    TERR_BRIT_EN_OP = (407, "Territorio Británico en Oceanía")
    TERR_FRAN_EN_OP = (408, "Territorio Francés en Oceanía")
    T_NORTEAM_EN_OP = (409, "Territorio Norteamericano en Oceanía")
    PPUA_NVA_GUINEA = (412, "Papúa Nueva Guinea")
    VANUATU = (415, "Vanuatu")
    KIRIBATI = (416, "Kiribati")
    MICRONESIA = (417, "Estados Federados de Micronesia")
    ISLAS_SALOMON = (418, "Islas Salomón")
    TUVALU = (419, "Tuvalu")
    BELAU = (420, "Belau")
    NIUE = (421, "Niue")
    POLINESIA_FRAN = (422, "Polinesia Francesa")
    NUEVA_CALEDONIA = (423, "Nueva Caledonia")
    ISLAS_MARIANAS = (424, "Islas Marianas")
    GUAM = (425, "Guam")
    TIMOR_ORIENTAL = (426, "Timor Oriental")
    ISLAS_COOK = (427, "Islas Cook")
    PORTUGAL = (501, "Portugal")
    ITALIA = (504, "Italia")
    FRANCIA = (505, "Francia")
    IRLANDA = (506, "Irlanda")
    DINAMARCA = (507, "Dinamarca")
    SUIZA = (508, "Suiza")
    AUSTRIA = (509, "Austria")
    REINO_UNIDO = (510, "Reino Unido")
    SUECIA = (511, "Suecia")
    FINLANDIA = (512, "Finlandia")
    NORUEGA = (513, "Noruega")
    BELGICA = (514, "Bélgica")
    HOLANDA = (515, "Holanda")
    ISLANDIA = (516, "Islandia")
    ESPANA = (517, "España")
    ALBANIA = (518, "Albania")
    RUMANIA = (519, "Rumanía")
    GRECIA = (520, "Grecia")
    U_R_S_S = (521, "Unión Soviética")
    TURQUIA = (522, "Turquía")
    MALTA = (523, "Malta")
    SANTA_SEDE = (524, "Ciudad del Vaticano")
    ANDORRA = (525, "Andorra")
    BULGARIA = (527, "Bulgaria")
    POLONIA = (528, "Polonia")
    HUNGRIA = (530, "Hungría")
    LUXEMBURGO = (532, "Luxemburgo")
    LIECHTENSTEIN = (534, "Liechtenstein")
    MONACO = (535, "Mónaco")
    SAN_MARINO = (536, "San Marino")
    ARMENIA = (540, "Armenia")
    AZERBAIJAN = (541, "Azerbaiyán")
    BELARUS = (542, "Bielorrusia")
    BOSNIA_HEZGVINA = (543, "Bosnia y Herzegovina")
    REPUBLICA_CHECA = (544, "República Checa")
    REP_ESLOVACA = (545, "República Eslovaca")
    REPUBLICA_DE_SE = (546, "Serbia")
    CROACIA = (547, "Croacia")
    ESLOVENIA = (548, "Eslovenia")
    ESTONIA = (549, "Estonia")
    GEORGIA = (550, "Georgia")
    KASAJSTAN = (551, "Kazajistán")
    KIRGISTAN = (552, "Kirguistán")
    LETONIA = (553, "Letonia")
    LITUANIA = (554, "Lituania")
    MACEDONIA = (555, "Macedonia")
    MOLDOVA = (556, "Moldavia")
    TADJIKISTAN = (557, "Tayikistán")
    TURKMENISTAN = (558, "Turkmenistán")
    UCRANIA = (559, "Ucrania")
    UZBEKISTAN = (560, "Uzbekistán")
    MONTENEGRO = (561, "Montenegro")
    RUSIA = (562, "Rusia")
    ALEMANIA = (563, "Alemania")
    GIBRALTAR = (565, "Gibraltar")
    GUERNSEY = (566, "Guernsey")
    ISLAS_DE_MAN = (567, "Isla de Man")
    JERSEY = (568, "Jersey")
    LOS_DEMAS = (888, "Los Demas")
    COMB_Y_LUBRIC = (901, "Comb y Lubric")
    RANCHO_DE_NAVES = (902, "Rancho de Naves")
    PESCA_EXTRA = (903, "Pesca Extra")
    ORIG_O_DEST_NO = (904, "Origen o Destino No")
    ZF_IQUIQUE = (905, "ZF Iquique")
    DEPOSITO_FRANCO = (906, "Depósito Franco")
    ZF_PARENAS = (907, "ZF Punta Arenas")
    ZF_ARICA_ZF_IND = (910, "ZF Arica Az Ind")
    CHILE = (997, "Chile")
    NAC_REPUTADA = (998, "Nac Reputada")
    OTROS = (999, "Otros")

    @property
    def xml_enum(self):
        return self.value[0]

    @property
    def description(self):
        return self.value[1]


class Puertos(Enum):
    NotSet = (0, "No Asignado")
    MONTREAL = (111, "Montreal")
    COSTA_DEL_PACIFICO_1 = (112, "Costa del Pacífico 1")
    HALIFAX = (113, "Halifax")
    VANCOUVER = (114, "Vancouver")
    SAINT_JOHN = (115, "Saint John")
    TORONTO = (116, "Toronto")
    OTROS_PUERTOS_CANADA = (117, "Otros Puertos Canadá")
    BAYSIDE = (118, "Bayside")
    PORT_CARTIES = (120, "Puerto Cartier")
    COSTA_DEL_ATLANTICO = (121, "Costa del Atlántico")
    PUERTOS_DEL_GOLFO_ME = (122, "Puertos del Golfo México")
    COSTA_DEL_PACIFICO_2 = (123, "Costa del Pacífico 2")
    QUEBEC = (124, "Quebec")
    PRINCE_RUPERT = (125, "Prince Rupert")
    HAMILTON = (126, "Hamilton")
    BOSTON = (131, "Boston")
    NEW_HAVEN = (132, "New Haven")
    BRIDGEPORT = (133, "Bridgeport")
    NEW_YORK = (134, "Nueva York")
    FILADELFIA = (135, "Filadelfia")
    BALTIMORE = (136, "Baltimore")
    NORFOLK = (137, "Norfolk")
    CHARLESTON = (139, "Charlestón")
    SAVANAH = (140, "Savannah")
    MIAMI = (141, "Miami")
    EVERGLADES = (142, "Everglades")
    JACKSONVILLE = (143, "Jacksonville")
    PALM_BEACH = (145, "Palm Beach")
    BATON_ROUGE = (146, "Baton Rouge")
    COLUMBRES = (147, "Columbres")
    PITTSBURGH = (148, "Pittsburgh")
    DULUTH = (149, "Duluth")
    MILWAUKEE = (150, "Milwaukee")
    TAMPA = (151, "Tampa")
    PENSACOLA = (152, "Pensacola")
    MOBILE = (153, "Mobile")
    NEW_ORLEANS = (154, "Nueva Orleans")
    PORT_ARTHUR = (155, "Port Arthur")
    GALVESTON = (156, "Galveston")
    CORPUS_CRISTI = (157, "Corpus Cristi")
    BROWNSVILLE = (158, "Brownsville")
    HOUSTON = (159, "Houston")
    OAKLAND = (160, "Oakland")
    STOCKTON = (161, "Stockton")
    SEATTLE = (171, "Seattle")
    PORTLAND = (172, "Portland")
    SAN_FRANCISCO = (173, "San Francisco")
    LOS_ANGELES = (174, "Los Angeles")
    LONG_BEACH = (175, "Long Beach")
    SAN_DIEGO = (176, "San Diego")
    OTROS_PUERTOS_EE_UU_ = (180, "Otros Puertos EEUU")
    LOS_VILOS = (199, "Los Vilos")
    PATACHE = (204, "Patache")
    CALBUCO = (205, "Calbuco")
    MICHILLA = (206, "Michilla")
    PUERTO_ANGAMOS = (207, "Puerto Angamos")
    POSEIDON = (208, "Poseidon")
    TRES_PUENTES = (209, "Tres Puentes")
    OTROS_PUERTOS_MEXICO = (210, "Otros Puertos México")
    TAMPICO = (211, "Tampico")
    COSTA_DEL_PACIFICO_3 = (212, "Costa del Pacífico 3")
    VERACRUZ = (213, "Veracruz")
    COATZACOALCOS = (214, "Coatzacoalcos")
    GUAYMAS = (215, "Guaymas")
    MAZATLAN = (216, "Mazatlán")
    MANZANILLO = (217, "Manzanillo")
    ACAPULCO = (218, "Acapulco")
    GOLFO_DE_MEXICO_OTRO = (219, "Golfo de México, Otro")
    ALTAMIRA = (220, "Altamira")
    CRISTOBAL = (221, "Cristobal")
    BALBOA = (222, "Balboa")
    COLON = (223, "Colón")
    OTROS_PTOS__PANAMA = (224, "Otros Puertos Panamá")
    OTROS_PTOS__COLOMBIA = (231, "Otros Puertos Colombia")
    BUENAVENTURA = (232, "Buenaventura")
    BARRANQUILLA = (233, "Barranquilla")
    OTROS_PTOS__ECUADOR = (241, "Otros Puertos Ecuador")
    GUAYAQUIL = (242, "Guayaquil")
    OTROS_PTOS__DE_PERU = (251, "Otros Puertos Perú")
    CALLAO = (252, "Callao")
    ILO = (253, "Ilo")
    IQUITOS = (254, "Iquitos")
    OTROS_PTOS_ARGENTINA = (261, "Otros Puertos Argentina")
    BUENOS_AIRES = (262, "Buenos Aires")
    NECOCHEA = (263, "Necochea")
    MENDOZA = (264, "Mendoza")
    CORDOBA = (265, "Córdoba")
    BAHIA_BLANCA = (266, "Bahía Blanca")
    COMODORO_RIVADAVIA = (267, "Comodoro Rivadavia")
    PUERTO_MADRYN = (268, "Puerto Madryn")
    MAR_DEL_PLATA = (269, "Mar del Plata")
    ROSARIO = (270, "Rosario")
    OTROS_PTOS_URUGUAY = (271, "Otros Puertos Uruguay")
    MONTEVIDEO = (272, "Montevideo")
    OTROS_PTOS_VENEZUELA = (281, "Otros Puertos Venezuela")
    LA_GUAIRA = (282, "La Guaira")
    MARACAIBO = (285, "Maracaibo")
    OTROS_PTOS_BRASIL = (291, "Otros Puertos Brasil")
    SANTOS = (292, "Santos")
    RIO_DE_JANEIRO = (293, "Río de Janeiro")
    RIO_GRANDE_DEL_SUR = (294, "Río Grande del Sur")
    PARANAGUA = (295, "Paranaguá")
    SAO_PAULO = (296, "Sao Paulo")
    SALVADOR = (297, "Salvador")
    OTROS_ANT_HOLANDESA = (301, "Otros Ant Holandesa")
    CURAZAO = (302, "Curazao")
    OTROS_PTOS_AMERICA = (399, "Otros Puertos América")
    SHANGAI = (411, "Shanghái")
    DAIREN = (412, "Dairen")
    OTROS_PTOS_DE_CHINA = (413, "Otros Puertos China")
    OTROS_PUERT_COREA_N = (420, "Otros Puertos Corea del Norte")
    NAMPO = (421, "Nampo")
    BUSAN = (422, "Busan")
    OTROS_PTOS__COREA_S = (423, "Otros Puertos Corea del Sur")
    MANILA = (431, "Manila")
    OTROS_PTOS_FILIPINAS = (432, "Otros Puertos Filipinas")
    OTROS_PTOS_JAPONESES = (441, "Otros Puertos Japoneses")
    OSAKA = (442, "Osaka")
    KOBE = (443, "Kobe")
    YOKOHAMA = (444, "Yokohama")
    NAGOYA = (445, "Nagoya")
    SHIMIZUI = (446, "Shimizui")
    MOJI = (447, "Moji")
    YAWATA = (448, "Yawata")
    FUKUYAMA = (449, "Fukuyama")
    KAOHSIUNG = (451, "Kaohsiung")
    KEELUNG = (452, "Keelung")
    OTROS_PTOS_TAIWAN = (453, "Otros Puertos Taiwan")
    KARHG_ISLAND = (461, "Karhg Island")
    OTROS_PTO_IRAN_NO_ES = (462, "Otros Puertos Iran No Es")
    CALCUTA = (471, "Calcuta")
    OTROS_PTOS__DE_INDIA = (472, "Otros Puertos India")
    CHALNA = (481, "Chalna")
    OTROS_PTO_BANGLADESH = (482, "Otros Puertos Bangladesh")
    OTROS_PTO_SINGAPURE = (491, "Otros Puertos Singapure")
    HONG_KONG = (492, "Hong Kong")
    OTROS_PTO_ASIATICOS = (499, "Otros Puertos Asiaticos")
    CONSTANZA = (511, "Constanza")
    OTROS_PTO_DE_RUMANIA = (512, "Otros Puertos Rumanía")
    VARNA = (521, "Varna")
    OTROS_PTOS_BULGARIA = (522, "Otros Puertos Bulgaria")
    BELGRADO = (533, "Belgrado")
    OTROS_PUERTOS_DE_SER = (534, "Otros Puertos Ser")
    PODGORITSA = (535, "Podgoritsa")
    OTROS_PUERTOS_DE_MON = (536, "Otros Puertos de Mon")
    OTROS_PUERTOS_DE_CRO = (537, "Otros Puertos de Cro")
    RIJEKA = (538, "Rijeka")
    OTROS_PTOS_DE_ITALIA = (541, "Otros Puertos de Italia")
    GENOVA = (542, "Genova")
    LIORNA_LIVORNO = (543, "Liora, Livorno")
    NAPOLES = (544, "Napoles")
    SALERNO = (545, "Salermo")
    AUGUSTA = (546, "Augusta")
    SAVONA = (547, "Savona")
    OTROS_PTOS_FRANCIA = (551, "Otros Puertos de Francia")
    LA_PALLICE = (552, "La Pallice")
    LE_HAVRE = (553, "Le Havre")
    MARSELLA = (554, "Marsella")
    BURDEOS = (555, "Burdeos")
    CALAIS = (556, "Calais")
    BREST = (557, "Brest")
    RUAN = (558, "Ruan")
    OTROS_PTOS_ESPANA = (561, "Otros Puertos de España")
    CADIZ = (562, "Cadiz")
    BARCELONA = (563, "Barcelona")
    BILBAO = (564, "Bilbao")
    HUELVA = (565, "Huelva")
    SEVILLA = (566, "Sevilla")
    TARRAGONA = (567, "Tarragona")
    ALGECIRAS = (568, "Algeciras")
    VALENCIA = (569, "Valencia")
    LIVERPOOL = (571, "Liverpool")
    LONDRES = (572, "Londres")
    ROCHESTER = (573, "Rochester")
    ETEN_SALVERRY = (574, "Eten Salverry")
    OTROS_PTOS_INGLATERR = (576, "Otros Puertos de Inglaterra")
    DOVER = (577, "Dover")
    PLYMOUTH = (578, "Plymouth")
    HELSINKI = (581, "Helsinki")
    OTROS_PTOS_FINLANDIA = (582, "Otros Puertos de Finlandia")
    HANKO = (583, "Hanko")
    KEMI = (584, "Kemi")
    KOKKOLA = (585, "Kokkola")
    KOTKA = (586, "Kotra")
    OULO = (587, "Oulo")
    PIETARSAARI = (588, "Piertarsaari")
    PORI = (589, "Pori")
    BREMEN = (591, "Bremen")
    HAMBURGO = (592, "Hamburgo")
    NUREMBERG = (593, "Nuremberg")
    FRANKFURT = (594, "Frankfurt")
    DUSSELDORF = (595, "Dusseldorf")
    OTROS_PTOS_ALEMANIA = (596, "Otros Puertos de Alemania")
    CUXHAVEN = (597, "Cuxhaven")
    ROSTOCK = (598, "Rostock")
    OLDENBURG = (599, "Oldenburg")
    AMBERES = (601, "Amberes")
    OTROS_PTO_BELGICA = (602, "Otros Puertos de Belgica")
    ZEEBRUGGE = (603, "Zeebrugge")
    GHENT = (604, "Ghent")
    OOSTENDE = (605, "Oostende")
    LISBOA = (611, "Lisboa")
    OTROSS_PTOS_PORTUGAL = (612, "Otros Puertos de Portugal")
    SETUBAL = (613, "Setubal")
    AMSTERDAM = (621, "Amsterdam")
    ROTTERDAM = (622, "Rotterdam")
    OTROS_PTOS_HOLANDA = (623, "Otros Puertos de Holanda")
    GOTEMBURGO = (631, "Gotemburgo")
    OTROS_PTOS_SUECIA = (632, "Otros Puertos de Suecia")
    MALMO = (633, "Malmo")
    HELSIMBORG = (634, "Helsimborg")
    KALMAR = (635, "Kalmar")
    AARHUS = (641, "Aarhus")
    COPENHAGEN = (642, "Copenhagen")
    OTROS_PTOS_DINAMARCA = (643, "Otros Puertos de Dinamarca")
    AALBORG = (644, "Aalborg")
    ODENSE = (645, "Odense")
    OSLO = (651, "Oslo")
    OTROS_PTO__NORUEGA = (652, "Otros Puertos de Noruega")
    STAVANGER = (653, "Stavanger")
    OTROS_PTOS_EUROPA = (699, "Otros Puertos de Europa")
    DURBAM = (711, "Durbam")
    CIUDAD_DEL_CABO = (712, "Ciudad del Cabo")
    OTROS_PTO_SUDAFFRICA = (713, "Otros Puertos de Sudáfrica")
    SALDANHA = (714, "Saldanha")
    PORT_ELIZABETH = (715, "Puerto Elizabeth")
    MOSSEL_BAY = (716, "Mossel Bay")
    EAST_LONDON = (717, "East London")
    OTROS_PTO_DE_AFRICA = (799, "Otros Puertos de África")
    SIDNEY = (811, "Sidney")
    FREMANTLE = (812, "Fremantle")
    OTROS_PTOS_AUSTRALIA = (813, "Otros Puertos de Australia")
    ADELAIDA = (814, "Adelaida")
    DARWIN = (815, "Darwin")
    GERALDTON = (816, "Geraldton")
    OTROS_PTOS__OCEANIA = (899, "Otros Puertos de Oceanía")
    LUBRIC_ = (900, "Lubric")
    ARICA = (901, "Arica")
    IQUIQUE = (902, "Iquique")
    ANTOFAGASTA = (903, "Antofagasta")
    COQUIMBO = (904, "Coquimbo")
    VALPARAISO = (905, "Valparaíso")
    SAN_ANTONIO = (906, "San Antonio")
    TALCAHUANO = (907, "Talcahuano")
    SAN_VICENTE = (908, "San Vicente")
    LIRQUEN = (909, "Lirquen")
    PUERTO_MONTT = (910, "Puerto Montt")
    CHACABUCO_PTO_AYSEN = (911, "Chacabuco Puerto Aysen")
    PUNTA_ARENAS = (912, "Punta Arenas")
    PATILLOS = (913, "Patillos")
    TOCOPILLA = (914, "Tocopilla")
    MEJILLONES = (915, "Mejillones")
    TALTAL = (916, "Taltal")
    CHANARAL_BARQUITO = (917, "Barquito de Chañaral")
    CALDERA = (918, "Caldera")
    CALDERILLA = (919, "Calderilla")
    HUASCO_GUACOLDA = (920, "Huasco Guacolda")
    QUINTERO = (921, "Quintero")
    JUAN_FERNANDEZ = (922, "Juan Fernandez")
    CONSTUTUCION = (923, "Constitución")
    TOME = (924, "Tomé")
    PENCO = (925, "Penco")
    CORONEL = (926, "Coronel")
    LOTA = (927, "Lota")
    LEBU = (928, "Lebu")
    ISLA_DE_PASCUA = (929, "Isla de Pascua")
    CORRAL = (930, "Corral")
    ANCUD = (931, "Ancud")
    CASTRO = (932, "Castro")
    QUELLON = (933, "Quellón")
    CHAITEN = (934, "Chaiten")
    TORTEL = (935, "Tortel")
    NATALES = (936, "Natales")
    GUARELLO = (937, "Guarello")
    PUERTO_ANDINO = (938, "Puerto Andino")
    PERCY = (939, "Percy")
    CLARENCIA = (940, "Clarencia")
    GREGORIO = (941, "Gregorio")
    CABO_NEGRO = (942, "Cabo Negro")
    PUERTO_WILLIAMS = (943, "Puerto Williams")
    TER_ANTARTICO_CHILEN = (944, "Territorio Chileno Antártico")
    AEROP__CARRIEL_SUR = (945, "Aeropuerto Carriel Sur")
    GUAYACAN = (946, "Guayacan")
    PASO_PEHUENCHE = (947, "Paso Pehuenche")
    VENTANAS = (948, "Ventanas")
    PINO_HACHADO = (949, "Pino Hachado")
    CALETA_COLOSO = (950, "Caleta Coloso")
    AGUAS_NEGRAS = (951, "Aguas Negras")
    ZONA_FRANCA_IQUIQUE = (952, "Zona Franca de Iquique")
    ZONA_FRANCA_PTA_AREN = (953, "Zona Franca de Punta Arenas")
    RIO_MAYER = (954, "Río Mayer")
    RIO_MOSCO = (955, "Río Mosco")
    VISVIRI = (956, "Visviri")
    CHACALLUTA = (957, "Chacalluta")
    CHUNGARA = (958, "Chungara")
    COLCHANE = (959, "Colchane")
    ABRA_DE_NAPA = (960, "Abra de Napa")
    OLLAGUE = (961, "Ollague")
    SAN_PEDRO_DE_ATACAMA = (962, "San Pedro de Atacama")
    SOCOMPA = (963, "Socompa")
    SAN_FRANCISCO_2 = (964, "San Francisco 2")
    LOS_LIBERTADORES = (965, "Los Libertadores")
    MAHUIL_MALAL = (966, "Mahuil Malal")
    CARDENAL_SAMORE = (967, "Cardenal Samore")
    PEREZ_ROSALES = (968, "Perez Rosales")
    FUTALEUFU = (969, "Futaleufu")
    PALENA_CARRENLEUFU = (970, "Palena Carrenleufu")
    PANGUIPULLI = (971, "Panguipulli")
    HUAHUM = (972, "Huahum")
    LAGO_VERDE = (973, "Lago Verde")
    APPELEG = (974, "Appeleg")
    PAMPA_ALTA = (975, "Pampa Alta")
    HUEMULES = (976, "Huemules")
    CHILE_CHICO = (977, "Chile Chico")
    BAKER = (978, "Baker")
    DOROTEA = (979, "Dorotea")
    CASAS_VIEJAS = (980, "Casas Viejas")
    MONTE_AYMOND = (981, "Monte Aymond")
    SAN_SEBASTIAN = (982, "San Sebastián")
    COYHAIQUE_ALTO = (983, "Coyhaique Alto")
    TRIANA = (984, "Triana")
    IBANEZ_PALAVICINI = (985, "Ibáñez Pallavicini")
    VILLA_OHIGGINS = (986, "Villa O'Higgins")
    AEROP_CHACALLUTA = (987, "Aeropuerto Internacional Chacalluta")
    AEROP_DIEGO_ARACENA = (988, "Aeropuerto Internacional General Diego Aracena Aguilar")
    AEROP_CERRO_MORENO = (989, "Aeropuerto Cerro Moreno")
    AEROP_EL_TEPUAL = (990, "Aeropuerto El Tepual")
    AEROP_C_I_DEL_CAMPO = (991, "Aeropuerto Presidente Carlos Ibáñez del Campo")
    AEROP_A_M_BENITEZ = (992, "Aeropuerto Arturo Merino Benítez")
    AEROD_LOA = (993, "Aeropuerto Loa")
    ARICA_TACNA = (994, "Arica, Tacna")
    ARICA_LA_PAZ = (995, "Arica, La Paz")
    OTROS_PTOS__CHILENOS = (997, "Otros Puertos Chilenos")
    PASO_JAMA = (998, "Paso Jama")
    
    @property
    def xml_enum(self):
        return self.value[0]

    @property
    def description(self):
        return self.value[1]
































